import * as React from 'react'
import Head from 'next/head'
import { AppProps } from 'next/app'
import { CacheProvider, EmotionCache } from '@emotion/react'
import { ApolloProvider } from '@apollo/client'
import { appWithTranslation, useTranslation } from 'next-i18next'

import CurrencyExchangeProvider from 'context/CurrencyExchangeContext'
import ColorModeContextProvider from 'context/ColorModeContext'
import DrawerContextProvider from 'context/DrawerContext'
import createEmotionCache from 'lib/createEmotionCache'
import client from 'apollo/client'

// Client-side cache, shared for the whole session of the user in the browser.
const clientSideEmotionCache = createEmotionCache()

interface MyAppProps extends AppProps {
  emotionCache?: EmotionCache
}

const App = (props: MyAppProps) => {
  const { Component, emotionCache = clientSideEmotionCache, pageProps } = props
  const { t } = useTranslation('common')
  return (
    <CacheProvider value={emotionCache}>
      <ApolloProvider client={client}>
        <Head>
          <title>{t('app-name')}</title>

          <meta charSet="utf-8" />
          <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
          <meta name="viewport" content="initial-scale=1, width=device-width" />

          <meta name="description" content="Generated by create next app" />
          <meta
            name="keywords"
            content="Owo finance, investments, personal finance"
          />

          <link rel="icon" href="/favicon.ico" />
          <link rel="manifest" href="/manifest.json" />
          <link rel="apple-touch-icon" href="/favicon.ico"></link>
        </Head>
        <ColorModeContextProvider>
          <DrawerContextProvider>
            <CurrencyExchangeProvider>
              <Component {...pageProps} />
            </CurrencyExchangeProvider>
          </DrawerContextProvider>
        </ColorModeContextProvider>
      </ApolloProvider>
    </CacheProvider>
  )
}

export default appWithTranslation(App)
